name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  # Перша робота: Виводить версії програмного забезпечення на рівні обробки даних
  PrintClientAndServerSoftwareVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Operating System (Client)
        run: uname -a  # Виводить версію ОС

      - name: Print Web Navigator (React)
        run: npx create-react-app --version  # Виводить версію React (як приклад веб-навігатора)

      - name: Print Node.js Version (Server 1)
        run: node --version  # Виводить версію Node.js

  # Друга робота: Виводить версії СУБД на рівні доступу до даних
  PrintDatabaseServerVersion:
    runs-on: ubuntu-latest
    needs: [PrintClientAndServerSoftwareVersions]
    steps:
      - name: Print PostgreSQL Version
        run: psql --version  # Виводить версію PostgreSQL
